/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class TAuthorization : TBase
{
  private List<string> _labels;

  public List<string> Labels
  {
    get
    {
      return _labels;
    }
    set
    {
      __isset.labels = true;
      this._labels = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool labels;
  }

  public TAuthorization() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.List) {
            {
              Labels = new List<string>();
              TList _list4 = iprot.ReadListBegin();
              for( int _i5 = 0; _i5 < _list4.Count; ++_i5)
              {
                string _elem6 = null;
                _elem6 = iprot.ReadString();
                Labels.Add(_elem6);
              }
              iprot.ReadListEnd();
            }
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("TAuthorization");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (Labels != null && __isset.labels) {
      field.Name = "labels";
      field.Type = TType.List;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteListBegin(new TList(TType.String, Labels.Count));
        foreach (string _iter7 in Labels)
        {
          oprot.WriteString(_iter7);
        }
        oprot.WriteListEnd();
      }
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder sb = new StringBuilder("TAuthorization(");
    sb.Append("Labels: ");
    sb.Append(Labels);
    sb.Append(")");
    return sb.ToString();
  }

}

