/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


/// <summary>
/// Represents a single cell and its value.
/// </summary>
#if !SILVERLIGHT
[Serializable]
#endif
public partial class TColumnValue : TBase
{
  private byte[] _family;
  private byte[] _qualifier;
  private byte[] _value;
  private long _timestamp;
  private byte[] _tags;

  public byte[] Family
  {
    get
    {
      return _family;
    }
    set
    {
      __isset.family = true;
      this._family = value;
    }
  }

  public byte[] Qualifier
  {
    get
    {
      return _qualifier;
    }
    set
    {
      __isset.qualifier = true;
      this._qualifier = value;
    }
  }

  public byte[] Value
  {
    get
    {
      return _value;
    }
    set
    {
      __isset.value = true;
      this._value = value;
    }
  }

  public long Timestamp
  {
    get
    {
      return _timestamp;
    }
    set
    {
      __isset.timestamp = true;
      this._timestamp = value;
    }
  }

  public byte[] Tags
  {
    get
    {
      return _tags;
    }
    set
    {
      __isset.tags = true;
      this._tags = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool family;
    public bool qualifier;
    public bool value;
    public bool timestamp;
    public bool tags;
  }

  public TColumnValue() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.String) {
            Family = iprot.ReadBinary();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.String) {
            Qualifier = iprot.ReadBinary();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 3:
          if (field.Type == TType.String) {
            Value = iprot.ReadBinary();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 4:
          if (field.Type == TType.I64) {
            Timestamp = iprot.ReadI64();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 5:
          if (field.Type == TType.String) {
            Tags = iprot.ReadBinary();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("TColumnValue");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (Family != null && __isset.family) {
      field.Name = "family";
      field.Type = TType.String;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteBinary(Family);
      oprot.WriteFieldEnd();
    }
    if (Qualifier != null && __isset.qualifier) {
      field.Name = "qualifier";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteBinary(Qualifier);
      oprot.WriteFieldEnd();
    }
    if (Value != null && __isset.value) {
      field.Name = "value";
      field.Type = TType.String;
      field.ID = 3;
      oprot.WriteFieldBegin(field);
      oprot.WriteBinary(Value);
      oprot.WriteFieldEnd();
    }
    if (__isset.timestamp) {
      field.Name = "timestamp";
      field.Type = TType.I64;
      field.ID = 4;
      oprot.WriteFieldBegin(field);
      oprot.WriteI64(Timestamp);
      oprot.WriteFieldEnd();
    }
    if (Tags != null && __isset.tags) {
      field.Name = "tags";
      field.Type = TType.String;
      field.ID = 5;
      oprot.WriteFieldBegin(field);
      oprot.WriteBinary(Tags);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder sb = new StringBuilder("TColumnValue(");
    sb.Append("Family: ");
    sb.Append(Family);
    sb.Append(",Qualifier: ");
    sb.Append(Qualifier);
    sb.Append(",Value: ");
    sb.Append(Value);
    sb.Append(",Timestamp: ");
    sb.Append(Timestamp);
    sb.Append(",Tags: ");
    sb.Append(Tags);
    sb.Append(")");
    return sb.ToString();
  }

}

