/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


/// <summary>
/// Used to perform Put operations for a single row.
/// 
/// Add column values to this object and they'll be added.
/// You can provide a default timestamp if the column values
/// don't have one. If you don't provide a default timestamp
/// the current time is inserted.
/// 
/// You can specify how this Put should be written to the write-ahead Log (WAL)
/// by changing the durability. If you don't provide durability, it defaults to
/// column family's default setting for durability.
/// </summary>
#if !SILVERLIGHT
[Serializable]
#endif
public partial class TPut : TBase
{
  private byte[] _row;
  private List<TColumnValue> _columnValues;
  private long _timestamp;
  private Dictionary<byte[], byte[]> _attributes;
  private TDurability _durability;
  private TCellVisibility _cellVisibility;

  public byte[] Row
  {
    get
    {
      return _row;
    }
    set
    {
      __isset.row = true;
      this._row = value;
    }
  }

  public List<TColumnValue> ColumnValues
  {
    get
    {
      return _columnValues;
    }
    set
    {
      __isset.columnValues = true;
      this._columnValues = value;
    }
  }

  public long Timestamp
  {
    get
    {
      return _timestamp;
    }
    set
    {
      __isset.timestamp = true;
      this._timestamp = value;
    }
  }

  public Dictionary<byte[], byte[]> Attributes
  {
    get
    {
      return _attributes;
    }
    set
    {
      __isset.attributes = true;
      this._attributes = value;
    }
  }

  /// <summary>
  /// 
  /// <seealso cref="TDurability"/>
  /// </summary>
  public TDurability Durability
  {
    get
    {
      return _durability;
    }
    set
    {
      __isset.durability = true;
      this._durability = value;
    }
  }

  public TCellVisibility CellVisibility
  {
    get
    {
      return _cellVisibility;
    }
    set
    {
      __isset.cellVisibility = true;
      this._cellVisibility = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool row;
    public bool columnValues;
    public bool timestamp;
    public bool attributes;
    public bool durability;
    public bool cellVisibility;
  }

  public TPut() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.String) {
            Row = iprot.ReadBinary();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.List) {
            {
              ColumnValues = new List<TColumnValue>();
              TList _list17 = iprot.ReadListBegin();
              for( int _i18 = 0; _i18 < _list17.Count; ++_i18)
              {
                TColumnValue _elem19 = new TColumnValue();
                _elem19 = new TColumnValue();
                _elem19.Read(iprot);
                ColumnValues.Add(_elem19);
              }
              iprot.ReadListEnd();
            }
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 3:
          if (field.Type == TType.I64) {
            Timestamp = iprot.ReadI64();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 5:
          if (field.Type == TType.Map) {
            {
              Attributes = new Dictionary<byte[], byte[]>();
              TMap _map20 = iprot.ReadMapBegin();
              for( int _i21 = 0; _i21 < _map20.Count; ++_i21)
              {
                byte[] _key22;
                byte[] _val23;
                _key22 = iprot.ReadBinary();
                _val23 = iprot.ReadBinary();
                Attributes[_key22] = _val23;
              }
              iprot.ReadMapEnd();
            }
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 6:
          if (field.Type == TType.I32) {
            Durability = (TDurability)iprot.ReadI32();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 7:
          if (field.Type == TType.Struct) {
            CellVisibility = new TCellVisibility();
            CellVisibility.Read(iprot);
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("TPut");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (Row != null && __isset.row) {
      field.Name = "row";
      field.Type = TType.String;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteBinary(Row);
      oprot.WriteFieldEnd();
    }
    if (ColumnValues != null && __isset.columnValues) {
      field.Name = "columnValues";
      field.Type = TType.List;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteListBegin(new TList(TType.Struct, ColumnValues.Count));
        foreach (TColumnValue _iter24 in ColumnValues)
        {
          _iter24.Write(oprot);
        }
        oprot.WriteListEnd();
      }
      oprot.WriteFieldEnd();
    }
    if (__isset.timestamp) {
      field.Name = "timestamp";
      field.Type = TType.I64;
      field.ID = 3;
      oprot.WriteFieldBegin(field);
      oprot.WriteI64(Timestamp);
      oprot.WriteFieldEnd();
    }
    if (Attributes != null && __isset.attributes) {
      field.Name = "attributes";
      field.Type = TType.Map;
      field.ID = 5;
      oprot.WriteFieldBegin(field);
      {
        oprot.WriteMapBegin(new TMap(TType.String, TType.String, Attributes.Count));
        foreach (byte[] _iter25 in Attributes.Keys)
        {
          oprot.WriteBinary(_iter25);
          oprot.WriteBinary(Attributes[_iter25]);
        }
        oprot.WriteMapEnd();
      }
      oprot.WriteFieldEnd();
    }
    if (__isset.durability) {
      field.Name = "durability";
      field.Type = TType.I32;
      field.ID = 6;
      oprot.WriteFieldBegin(field);
      oprot.WriteI32((int)Durability);
      oprot.WriteFieldEnd();
    }
    if (CellVisibility != null && __isset.cellVisibility) {
      field.Name = "cellVisibility";
      field.Type = TType.Struct;
      field.ID = 7;
      oprot.WriteFieldBegin(field);
      CellVisibility.Write(oprot);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder sb = new StringBuilder("TPut(");
    sb.Append("Row: ");
    sb.Append(Row);
    sb.Append(",ColumnValues: ");
    sb.Append(ColumnValues);
    sb.Append(",Timestamp: ");
    sb.Append(Timestamp);
    sb.Append(",Attributes: ");
    sb.Append(Attributes);
    sb.Append(",Durability: ");
    sb.Append(Durability);
    sb.Append(",CellVisibility: ");
    sb.Append(CellVisibility== null ? "<null>" : CellVisibility.ToString());
    sb.Append(")");
    return sb.ToString();
  }

}

